name: neopolis
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: ^1.1.0
  get_it: ^2.0.1
  flutter_bloc: ^0.21.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  http: ^0.12.0+2
  data_connection_checker: ^0.3.4
  auto_size_text: ^2.1.0
  mercury_client: ^1.1.12
  rflutter_alert: ^1.1.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
 uses-material-design: true

 assets:
    - Assets/

 fonts:
  - family: SourceSansPro
    fonts:
    - asset: Assets/SourceSansPro-Black.ttf
      weight: 900
    - asset: Assets/SourceSansPro-Bold.ttf
      weight: 700
    - asset: Assets/SourceSansPro-ExtraLight.ttf
      weight: 100
    - asset: Assets/SourceSansPro-Light.ttf
      weight: 300
    - asset: Assets/SourceSansPro-Regular.ttf
    - asset: Assets/SourceSansPro-SemiBold.ttf
      weight: 600